version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

workflow:
  deploy-docker-and-nais:
    jobs:
      - deploy-docker:
          docker:
            - image: 'circleci/openjdk:11-jdk'
          steps:
            - checkout
            - run: ./gradlew check shadowJar
            - nais/docker-deploy:
                image: navikt/pleiepengesoknad-mottak

      - deploy-dev:
          requires:
            - deploy-docker
          filters:
            branches:
              only: master
          steps:
            - nais/deploy:
                build-and-push-docker-image: false
                repo: navikt/pleiepengesoknad-mottak
                image: navikt/pleiepengesoknad-mottak
                github-app-id: 35124
                nais-template: nais/dev-fss.yml
                environment: dev-fss
                team: dusseldorf